	function genSearch(){
	
		//CREATE A THING TO HAVE THE THINGS
	
			if(//DEDMAN CHECKED)
				//RETURN DEDMAN
			if(//LYLE CHECKED)
				//RETURN LYLE
			if(//COX CHECKED)
				//RETURN COX
			if(//MEADOWS CHECKED)
				//RETURN MEADOWS
			if(//SIMMONS CHECKED)
				//RETURN SIMMONS
			if(//ANTHROPOLOGY CHECKED)
				//RETURN ANTHROPOLOGY
			if(//BIOSCIENCE CHECKED)
				//RETURN BIOSCIENCE
			if(//CHEMISTRY CHECKED)
				//RETURN CHEMISTRY
			if(//EARTH SCIENCE CHECKED)
				//RETURN SCIENCE
			if(//ECONOMICS CHECKED)
				//RETURN ECONOMICS
			if(//ENGLISH CHECKED)
				//RETURN ENGLISH
			if(//HISTORY CHECKED)
				//RETURN HISTORY
			if(//MATH CHECKED)
				//RETURN MATH
			if(//PHILOSOPHY CHECKED)
				//RETURN PHILOSOPHY
			if(//PHYSICS CHECKED)
				//RETURN PHYSICS
			if(//POLISCI CHECKED)
				//RETURN POLISCI
			if(//PSYCHOLOGY CHECKED)
				//RETURN PSYCHOLOGY
			if(//RELIGIONSCI CHECKED)
				//RETURN RELIGIONSCI
			if(//SOCIOLOGY CHECKED)
				//RETURN SOCIOLOGY
			if(//STATSCIENCE CHECKED)
				//RETURN STATSCIENCE
			if(//WORLDLANG CHECKED)
				//RETURN WORLDLANG
			if(//CIVILENVIROENGIN CHECKED)
				//RETURN CIVILENVIROENGIN
			if(//CSCSE CHECKED)
				//RETURN CSCSE
			if(//EE CHECKED)
				//RETURN EE
			if(//MANAGESCIENCE CHECKED)
				//RETURN MANAGESCIENCE
			if(//MECHENGIN CHECKED)
				//RETURN MECHENGIN
			if(//ACCOUNTING CHECKED)
				//RETURN ACCOUNTING
			if(//FINANCE CHECKED)
				//RETURN FINANCE
			if(//MARKETING CHECKED)
				//RETURN MARKETING
			if(//MANAGEMENT CHECKED)
				//RETURN MANAGEMENT
			if(//REALESTATE CHECKED)
				//RETURN REALESTATE
			if(//RISKMANAGE CHECKED)
				//RETURN RISKMANAGE
			if(//ADVERTISING CHECKED)
				//RETURN ADVERTISING
			if(//ART CHECKED)
				//RETURN ART
			if(//ARTHISTORY CHECKED)
				//RETURN ARTHISTORY
			if(//ARTMANAGE CHECKED)
				//RETURN ARTMANAGE
			if(//COMMUNICATION CHECKED)
				//RETURN COMMUNICATION
			if(//CREATIVECOMP CHECKED)
				//RETURN CREATIVECOMP
			if(//DANCE CHECKED)
				//RETURN DANCE
			if(//FILMMEDIAART CHECKED)
				//RETURN FILMMEDIAART
			if(//JOURNALISM CHECKED)
				//RETURN JOURNALISM
			if(//MUSIC CHECKED)
				//RETURN MUSIC
			if(//THEATRE CHECKED)
				//RETURN THEATRE
			if(//APPLIEDPHYS CHECKED)
				//RETURN APPLIEDPHYS
			if(//COUNSELING CHECKED)
				//RETURN COUNSELING
			if(//DISPUTERESOLUTION CHECKED)
				//RETURN DISPUTERESOLUTION
			if(//HIGHERED CHECKED)
				//RETURN HIGHERED
			if(//SPORTSMANAGE CHECKED)
				//RETURN SPORTSMANAGE
			if(//TEACHERED CHECKED)
				//RETURN TEACHERED
			if(//WELLNESS CHECKED)
				//RETURN WELLNESS
				
				
			//CHECK FOR SIMILARITIES/SORT PROPERLY
			
			//RETURN ALL OPS
			
				
		}